create table public.todos (
  id bigint generated by default as identity not null,
  title text null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null default gen_random_uuid (),
  "Completed" boolean not null default false,
  constraint todos_pkey primary key (id)
) TABLESPACE pg_default;
create policy "Enable delete for users based on user_id"
on "public"."todos"
as PERMISSIVE
for DELETE
to public
using (
  (( SELECT uid() AS uid) = user_id)
);

create policy "Enable insert for users based on user_id"
on "public"."todos"
as PERMISSIVE
for INSERT
to public
with check (
  (( SELECT uid() AS uid) = user_id)
);

create policy "Enable read access for all users"
on "public"."todos"
as PERMISSIVE
for SELECT
to public
using (
  true
);

create policy "Policy with table joins"
on "public"."todos"
as PERMISSIVE
for UPDATE
to public
using (
  (( SELECT uid() AS uid) = user_id)
);
alter table public.todos enable row level security;
