create table public.todos (
  id bigint generated by default as identity not null,
  title text null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null default gen_random_uuid (),
  completed boolean not null default false,
  constraint todos_pkey primary key (id)
) TABLESPACE pg_default;

create policy "Enable delete for users based on user_id"
on "public"."todos"
as PERMISSIVE
for DELETE
to public
using (
  (( SELECT uid() AS uid) = user_id)
);

create policy "Enable insert for users based on user_id"
on "public"."todos"
as PERMISSIVE
for INSERT
to public
with check (
  (( SELECT uid() AS uid) = user_id)
);

create policy "Enable read access for all users"
on "public"."todos"
as PERMISSIVE
for SELECT
to public
using (
  true
);

create policy "Policy with table joins"
on "public"."todos"
as PERMISSIVE
for UPDATE
to public
using (
  (( SELECT uid() AS uid) = user_id)
);
alter table public.todos enable row level security;

create or replace function select_todo()
returns setof todos
language plpgsql
as $$
begin
    return query
    select *
    from todos
    where user_id = auth.uid()
    order by id desc;
end;
$$;

create or replace function insert_todo(p_title text)
returns setof todos
language plpgsql
as $$
begin
    return query
    insert into todos (title, user_id)
    values (p_title, auth.uid())
    returning *;
end;
$$;
create or replace function delete_todo(p_id int8)
returns setof todos
language plpgsql
as $$
begin
    return query
    delete from todos
    where id = p_id
      and user_id = auth.uid()
    returning *;
end;
$$;

create or replace function toggle_todo(p_id int8)
returns setof todos 
language plpgsql
as $$
begin
    return query
    update todos
    set completed = not completed
    where id = p_id
      and user_id = auth.uid()
    returning *;
end;
$$;
