create table public.todos (
  id bigint generated by default as identity not null,
  title text null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null default gen_random_uuid (),
  "Completed" boolean not null default false,
  constraint todos_pkey primary key (id)
) TABLESPACE pg_default;
alter policy "Enable delete for users based on user_id"
on "public"."todos"
to public
using (
  (( SELECT uid() AS uid) = user_id)
);

alter policy "Enable insert for users based on user_id"
on "public"."todos"
to public
with check (
  (( SELECT uid() AS uid) = user_id)
);

alter policy "Enable read access for all users"
on "public"."todos"
to public
using (
  true
);

alter policy "Policy with table joins"
on "public"."todos"
to public
using (
  (( SELECT uid() AS uid) = user_id)
);
